=== Kate0528/Cat-Adoption-Site/XMLandXSD/cat.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="catBase">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="about">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="title"/>
                            <xs:element name="author">
                                <xs:complexType>
                                    <xs:attribute name="fistName"/>
                                    <xs:attribute name="lastName"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element ref="description"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="breeds">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="breed"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="alphabeticalIndex">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="letter">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element ref="name"/>
                                        <xs:element maxOccurs="unbounded" minOccurs="0"
                                            ref="catRefId"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="cats">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="cat" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element ref="name"/>
                                        <xs:element ref="description"/>
                                        <xs:element name="specs">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element name="breed"> </xs:element>
                                                  <xs:element name="gender">
                                                  <xs:simpleType>
                                                  <xs:restriction base="xs:string">
                                                  <xs:enumeration value="Female"/>
                                                  <xs:enumeration value="Male"/>
                                                  </xs:restriction>
                                                  </xs:simpleType>
                                                  </xs:element>
                                                  <xs:element name="spayed" type="xs:boolean"/>
                                                  <xs:element name="size">
                                                  <xs:simpleType>
                                                  <xs:restriction base="xs:string">
                                                  <xs:enumeration value="Small"/>
                                                  <xs:enumeration value="Medium"/>
                                                  <xs:enumeration value="Large"/>
                                                  </xs:restriction>
                                                  </xs:simpleType>
                                                  </xs:element>
                                                  <xs:element name="color"/>
                                                  <xs:element name="declawed" type="xs:boolean"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="adoptionPrice"/>
                                        <xs:element name="location"> </xs:element>
                                        <xs:element name="site"> </xs:element>
                                        <xs:element name="images">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element maxOccurs="unbounded" name="image">
                                                  <xs:complexType>
                                                  <xs:attribute name="fileName" type="xs:anyURI"
                                                  use="required"/>
                                                  <xs:attribute name="caption"/>
                                                  </xs:complexType>
                                                  </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="relatedCats">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element maxOccurs="unbounded" ref="catRefId"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="source">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element maxOccurs="unbounded"
                                                  name="sourceRefId" type="xs:IDREF"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute ref="id" use="required"/>
                                    <xs:attribute ref="age"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="sequences">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="sequence">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element maxOccurs="unbounded" ref="catRefId"/>
                                    </xs:sequence>
                                    <xs:attribute ref="age"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="sourceDefs">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="sourceDef">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element ref="name"/>
                                        <xs:element name="url"/>
                                        <xs:element ref="description"/>
                                    </xs:sequence>
                                    <xs:attribute ref="id" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="description">
        <xs:complexType>
            <xs:group maxOccurs="unbounded" ref="block"/>
        </xs:complexType>
    </xs:element>
    <xs:attribute name="id" type="xs:ID"/>
    <xs:element name="name"/>
    <xs:element name="breed">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="name"/>
                <xs:element maxOccurs="unbounded" minOccurs="0" ref="catRefId"/>
                <xs:element maxOccurs="unbounded" minOccurs="0" ref="breed"/>
            </xs:sequence>
            <xs:attribute name="breedId" type="xs:ID"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="catRefId" type="xs:IDREF"/>
    <xs:group name="block">
        <xs:choice>
            <xs:element ref="p"/>
            <xs:element ref="ul"/>
            <xs:element ref="ol"/>
            <xs:element minOccurs="0" ref="br"/>
            <xs:element ref="table"/>
            <xs:element name="media">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element ref="title"/>
                        <xs:element minOccurs="0" name="caption">
                            <xs:complexType mixed="true">
                                <xs:group maxOccurs="unbounded" minOccurs="0" ref="inline"/>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    <xs:attribute ref="id" use="required"/>
                    <xs:attribute name="url" type="xs:string" use="required"/>
                    <xs:attribute name="type" use="required">
                        <xs:simpleType>
                            <xs:restriction base="xs:NMTOKEN">
                                <xs:enumeration value="imageWeb"/>
                                <xs:enumeration value="imageLocal"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                    <xs:attribute name="style" type="xs:string"/>
                </xs:complexType>
            </xs:element>
            <xs:element ref="editor"/>
        </xs:choice>
    </xs:group>
    <xs:group name="inline">
        <xs:choice>
            <xs:element minOccurs="0" ref="b"/>
            <xs:element minOccurs="0" ref="i"/>
            <xs:element minOccurs="0" ref="u"/>
            <xs:element minOccurs="0" ref="xref"/>
            <xs:element minOccurs="0" name="pubMentioned"/>
        </xs:choice>
    </xs:group>
    <xs:element name="li">
        <xs:complexType mixed="true">
            <xs:group maxOccurs="unbounded" minOccurs="0" ref="inline"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="p">
        <xs:complexType mixed="true">
            <xs:group maxOccurs="unbounded" minOccurs="0" ref="inline"/>
        </xs:complexType>
    </xs:element>
    <xs:element fixed="" name="br" nillable="true"/>
    <xs:element name="hr"/>
    <xs:element name="ul">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element ref="li"/>
                <xs:element minOccurs="0" ref="ul"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <xs:element name="ol">
        <xs:complexType>
            <xs:sequence maxOccurs="unbounded">
                <xs:element maxOccurs="unbounded" ref="li"/>
                <xs:element minOccurs="0" ref="ol"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="table">
        <xs:complexType>
            <xs:sequence maxOccurs="unbounded" minOccurs="0">
                <xs:element maxOccurs="unbounded" name="tr">
                    <xs:complexType mixed="false">
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="td">
                                <xs:complexType mixed="true">
                                    <xs:choice maxOccurs="unbounded">
                                        <xs:group ref="block"/>
                                    </xs:choice>
                                    <xs:attribute name="style" type="xs:string" use="optional"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="style" type="xs:string" use="optional"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="border" type="xs:string" use="optional"/>
            <xs:attribute name="cellSpacing" type="xs:string" use="optional"/>
            <xs:attribute name="cellPadding" type="xs:string" use="optional"/>
            <xs:attribute name="style" type="xs:string" use="optional"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="i"/>
    <xs:element name="b"/>
    <xs:element name="u"/>
    <xs:element name="editor">
        <xs:complexType mixed="true">
            <xs:attribute name="showEdits" type="xs:boolean"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="xref">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="xrefText">
                    <xs:complexType mixed="true">
                        <xs:sequence>
                            <xs:element name="hotText"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute ref="id" use="required"/>
            <xs:attribute name="type" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:NMTOKEN">
                        <xs:enumeration value="off"/>
                        <xs:enumeration value="web"/>
                        <xs:enumeration value="local"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="dest" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="title"/>
    <xs:attribute name="age"/>
</xs:schema>

=== Kate0528/Cat-Adoption-Site/XMLandXSD/cat.xml
<?xml version="1.0" encoding="UTF-8"?>
<catBase xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="cat.xsd">
    <about>
        <title>Cat Adoption Platform</title>
        <author fistName="Yufei" lastName="Li"/>
        <description>
            <p>Yufei is a second-year graduate student in the iSchool. She is specialized in <b>Data
                    Science</b> and <b>Business Intelligence</b>.</p>
            <br/>
            <p>In her spare time, she loves</p>
            <ul>
                <li>Swimming</li>
                <li>Playing with <i>cats</i></li>
            </ul>
            <br/>
        </description>
    </about>
    <breeds>
        <breed breedId="Breed">
            <name>Breeds</name>
            <breed breedId="Breed_0">
                <name>Domestic Cats</name>
                <breed breedId="Breed_01">
                    <name>Domestic Medium Hair/Mix</name>
                    <catRefId>CAT_40667429</catRefId>
                    <catRefId>CAT_40722176</catRefId>
                    <catRefId>CAT_40627497</catRefId>
                    <catRefId>CAT_40565883</catRefId>
                    <catRefId>CAT_40722239</catRefId>
                    <catRefId>CAT_40618814</catRefId>
                    <catRefId>CAT_40583096</catRefId>
                </breed>
                <breed breedId="Breed_02">
                    <name>Domestic Longhair/Mix</name>
                    <catRefId>CAT_40492066</catRefId>
                    <catRefId>CAT_40722192</catRefId>
                </breed>
                <breed breedId="Breed_03">
                    <name>Domestic Shorthair/Mix</name>
                    <catRefId>CAT_40722652</catRefId>
                    <catRefId>CAT_40683211</catRefId>
                    <catRefId>CAT_40693257</catRefId>
                    <catRefId>CAT_40598525</catRefId>
                    <catRefId>CAT_40722228</catRefId>
                    <catRefId>CAT_39360040</catRefId>
                </breed>
            </breed>
        </breed>

    </breeds>
    <alphabeticalIndex>
        <letter>
            <name>A-G</name>
            <catRefId>CAT_40667429</catRefId>
            <catRefId>CAT_40722176</catRefId>
            <catRefId>CAT_40492066</catRefId>
            <catRefId>CAT_40722652</catRefId>
            <catRefId>CAT_40627497</catRefId>
            <catRefId>CAT_40722192</catRefId>
            <catRefId>CAT_40683211</catRefId>
        </letter>
        <letter>
            <name>H-M</name>
            <catRefId>CAT_40693257</catRefId>
            <catRefId>CAT_40598525</catRefId>
            <catRefId>CAT_40722239</catRefId>
            <catRefId>CAT_40722228</catRefId>
            <catRefId>CAT_40565883</catRefId>
        </letter>
        <letter>
            <name>N-Z</name>
            <catRefId>CAT_39360040</catRefId>
            <catRefId>CAT_40618814</catRefId>
            <catRefId>CAT_40583096</catRefId>
        </letter>
    </alphabeticalIndex>
    <cats>
        <cat id="CAT_40667429" age="1 year 6 month 10 days">
            <name>Brooklynn</name>
            <description>
                <p><b>Brooklynn</b> is a gorgeous one and a half year old tuxedo ready to go home!
                    Brooklynn came to <pubMentioned>Homeward</pubMentioned>
                    <xref id="homeward" type="web" dest="https://www.homewardpet.org/events-new/">
                        <xrefText> (<hotText>https://www.homewardpet.org/events-new/</hotText>)
                        </xrefText>
                    </xref> after her family was no longer able to care for her. She has lived with
                    cats and dogs before and did well with both.</p>
                <p>It is:</p>
                <ul>
                    <li>soft</li>
                    <li>lovely</li>
                </ul>
                <p>Come meet <b>Brooklynn</b> today!</p>
                <p>Brooklynn will likely do well with <i>slightly older kids</i> that can handle her
                    gently and participate in her care. </p>
                <br/>
            </description>
            <specs>
                <breed>Domestic Medium Hair/Mix</breed>
                <gender>Female</gender>
                <spayed>true</spayed>
                <size>Medium</size>
                <color>Black/White</color>
                <declawed>false</declawed>
            </specs>
            <adoptionPrice>100 dollars</adoptionPrice>
            <location>Cat Room </location>
            <site>Homeward Pet Adoption Center</site>
            <images>
                <image fileName="CAT_40667429.jpg" caption="Brooklynn"/>
            </images>
            <relatedCats>
                <catRefId>CAT_40722652</catRefId>
                <catRefId>CAT_40722228</catRefId>
            </relatedCats>
            <source>
                <sourceRefId>Brooklynn</sourceRefId>
            </source>
        </cat>
        <cat id="CAT_40722176" age="6 months 4 days">
            <name>Bronco</name>
            <description>
                <p>Bronco is a sweet 6 month old adolescent that is ready romp around with his new
                    family! Bronco, like most other young cats, has plenty of energy, and would do
                    best in a home that will give him lots of playtime. We don't know if Bronco has
                    lived with other cats or dogs before, so introductions should be done slowly.
                    Bronco would likely do best with slightly older kids that understand how to
                    handle him gently.</p>
                <br/>
            </description>
            <specs>
                <breed>Domestic Medium Hair/Mix</breed>
                <gender>Male</gender>
                <spayed>true</spayed>
                <size>Medium</size>
                <color>Black/Smoke</color>
                <declawed>false</declawed>
            </specs>
            <adoptionPrice>100 dollars</adoptionPrice>
            <location>Cat Room </location>
            <site>Homeward Pet Adoption Center</site>
            <images>
                <image fileName="CAT_40722176.jpg" caption="Bronco"/>
            </images>
            <relatedCats>
                <catRefId>CAT_40693257</catRefId>
            </relatedCats>
            <source>
                <sourceRefId>Bronco</sourceRefId>
            </source>
        </cat>
        <cat id="CAT_40492066" age="5 years 1 month 7 days">
            <name>Bugsy</name>
            <description>
                <p>Bugsy is a Staff Pick! Meet Bugsy! This adorably fluffy orange tabby is looking
                    for the loving home he so deserves. Bugsy was rescued from a hoarding situation
                    and was in need of medical care when he arrived. Bugsy had an old injury to one
                    of his eyes, and that eye needed to be removed. He is now on the mend and
                    healing well, and will adjust to life with just one eye without any issues.
                    Bugsy is understandably feeling a little shy in the busy shelter, but don't pass
                    him by! He is a super sweet and gentle kitty, whose personality will start to
                    blossom once he feels safe. With love and patience, we think this guy could be
                    compatible with gentle older children that can give him space while he adjusts
                    to his new home. Bugsy is positive for feline immunodeficiency virus - an easy
                    illness to manage (though he should be the only cat in the home, or live with
                    other FIV positive cats). We are not sure if Bugsy has lived with dogs before,
                    so slow and gradual introductions are recommended. Come in and meet Bugsy
                    today!</p>
                <br/>
            </description>
            <specs>
                <breed>Domestic Longhair/Mix</breed>
                <gender>Male</gender>
                <spayed>true</spayed>
                <size>Medium</size>
                <color>Orange</color>
                <declawed>false</declawed>
            </specs>
            <adoptionPrice>75 dollars</adoptionPrice>
            <location> Cat Room </location>
            <site>Homeward Pet Adoption Center</site>
            <images>
                <image fileName="CAT_40492066.jpg" caption="Bugsy"/>
            </images>
            <relatedCats>
                <catRefId>CAT_40627497</catRefId>
                <catRefId>CAT_40683211</catRefId>
                <catRefId>CAT_40565883</catRefId>
                <catRefId>CAT_40618814</catRefId>
                <catRefId>CAT_40583096</catRefId>
            </relatedCats>
            <source>
                <sourceRefId>Bugsy</sourceRefId>
            </source>
        </cat>
        <cat id="CAT_40722652" age="2 months 11 days">
            <name>Cupid</name>
            <description>
                <p> Cupid is a playful kitten that is ready to find his forever home! He is a very
                    curious and active kitten that loves playing with feather toys and chasing
                    anything that makes a crinkling sound. He definitely needs another kitten buddy
                    at home! All kittens are active and playful and looking for homes that can
                    provide them with daily playtime and lots of interaction - it is important for
                    kittens to get handled regularly so they get used to being pet and touched. They
                    also need to be taught that hands are not toys and skin is not for biting. Due
                    to their social needs and energy levels, Homeward Pet advises that kittens be
                    adopted in pairs or into homes with another young cat. Kittens are fragile and
                    require careful handling, so we recommend that families with children under 5
